In [1]:
import pandas as pd

## Reading Data

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df.head()

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
0   98.016161         0   68          0           0              0
1  101.198672         0   40          1          -1              0
2   99.366483         0   19          1          -1              1
3   98.452129         1    9          1           0              0
4   99.948420         0   50          0           1              1

In [4]:
df.tail()

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
2994   99.450186         0   28          0           1              1
2995   98.776229         0   30          0          -1              1
2996   99.371848         0   83          1           1              1
2997  101.289304         0   23          1          -1              1
2998   98.758189         0   70          0          -1              1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2999 entries, 0 to 2998
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   fever          2999 non-null   float64
 1   bodyPain       2999 non-null   int64  
 2   age            2999 non-null   int64  
 3   runnyNose      2999 non-null   int64  
 4   diffBreath     2999 non-null   int64  
 5   infectionProb  2999 non-null   int64  
dtypes: float64(1), int64(5)
memory usage: 140.7 KB


In [6]:
df['bodyPain'].value_counts()

0    1524
1    1475
Name: bodyPain, dtype: int64

In [7]:
df['fever'].value_counts()

100.442404    1
99.291395     1
99.203390     1
100.212807    1
100.018242    1
             ..
99.098682     1
101.231479    1
101.653475    1
99.584261     1
101.949213    1
Name: fever, Length: 2999, dtype: int64

In [8]:
df.describe()

fever     bodyPain          age    runnyNose   diffBreath  infectionProb
count  2999.000000  2999.000000  2999.000000  2999.000000  2999.000000    2999.000000
mean     99.973366     0.491831    50.967989     0.498166    -0.005669       0.504502
std       1.147738     0.500017    28.547392     0.500080     0.822244       0.500063
min      98.004697     0.000000     1.000000     0.000000    -1.000000       0.000000
25%      98.966920     0.000000    27.000000     0.000000    -1.000000       0.000000
50%      99.974832     0.000000    52.000000     0.000000     0.000000       1.000000
75%     100.944268     1.000000    75.000000     1.000000     1.000000       1.000000
max     101.998756     1.000000   100.000000     1.000000     1.000000       1.000000

## Train Test spliting

In [9]:
import numpy as np

In [10]:
def data_split(data, ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data) * ratio) #sets a size for test data
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]

In [11]:
np.random.permutation(5) #gives an permutation from 0 to n-1

array([0, 4, 3, 1, 2])

In [12]:
train, test = data_split(df, 0.2)

In [13]:
train

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
1103  100.862367         1   38          0           0              1
1569  101.098414         1   22          1          -1              0
2229  101.425967         0   79          0           1              0
2296   98.566469         0   52          1          -1              0
1800  100.157796         0   63          0           1              1
...          ...       ...  ...        ...         ...            ...
1638   98.633416         0   59          0          -1              0
1095  100.198518         0   93          1          -1              0
1130   99.924918         0   85          1          -1              0
1294  101.794233         1   69          0           0              0
860   100.261191         1   27          1          -1              0

[2400 rows x 6 columns]

In [14]:
test

fever  bodyPain  age  runnyNose  diffBreath  infectionProb
1376   98.307846         0   71          0           1              0
932   101.610346         1    4          0           1              0
144   100.867709         1   84          1          -1              1
1752   98.657349         1    1          0          -1              0
51     99.012306         1   81          1           0              0
...          ...       ...  ...        ...         ...            ...
842    98.092780         0    6          1          -1              0
637    99.069413         0   43          1           0              1
695   101.827688         1   62          1           0              0
226   101.937126         1   92          0           0              0
2603  100.967165         1   45          1          -1              0

[599 rows x 6 columns]

In [15]:
X_train = train[['fever', 'bodyPain', 'age', 'runnyNose', 'diffBreath']].to_numpy()
X_test = test[['fever', 'bodyPain', 'age', 'runnyNose', 'diffBreath']].to_numpy()
Y_train = train[['infectionProb']].to_numpy().reshape(2400, )
Y_test = test[['infectionProb']].to_numpy().reshape(599, )

In [16]:
X_train

array([[100.8623673 ,   1.        ,  38.        ,   0.        ,
          0.        ],
       [101.0984136 ,   1.        ,  22.        ,   1.        ,
         -1.        ],
       [101.4259674 ,   0.        ,  79.        ,   0.        ,
          1.        ],
       ...,
       [ 99.92491809,   0.        ,  85.        ,   1.        ,
         -1.        ],
       [101.7942328 ,   1.        ,  69.        ,   0.        ,
          0.        ],
       [100.2611906 ,   1.        ,  27.        ,   1.        ,
         -1.        ]])

In [17]:
Y_train

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
clf = LogisticRegression()
clf.fit(X_train, Y_train)

LogisticRegression()

In [22]:
inputPara = [100, 1, 55, 1, 1]
inf_prob = clf.predict_proba([inputPara])[0][1]

In [23]:
inf_prob

0.5133954781084168